[package]
name = "near-contract-minimal-test"
version = "0.1.0"
edition = "2021"

[dependencies]
near-workspaces = "0.16.0"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["macros"] }
